name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Prepare Dependencies
        run: |
          flutter pub get
      
      - name: Build
        run: |
          flutter build web --release --base-href "/frc6907-scouting-app/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build/web
