name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Prepare Dependencies
        run: |
          flutter pub get
      
      - name: Build & Upload
        run: |
          flutter build web --release --web-renderer html
          cd build/web
          git add -A
          git commit -m 'gh-action deploy'
          git remote add origin https://github.com/singularity-s0/frc6907-scouting-app.git
          git push -f -u origin gh-pages
